services:
  - type: web
    name: hlp-loyalty-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false